var slovnik={
"A bird in the hand is worth two in the bush": ["Lepší vrabec v hrsti nežli holub na střeše"],
"A blessing in disguise": ["Štěstí v neštěstí"],
"A dime a dozen": ["Něco obyčejného, běžného"],
"A gift from the gods":["dar od boha; nečekaná výhoda"],
"A little bird told me.":["Štěbetají si to vrabci na střeše."],
"A little learning is a dangerous thing": ["Ze všeho nejhorší jsou amatéři"],
"A load of rubbish":["snůška nesmyslů (žvástů)"],
"A mine of information":["chodící kniha;všechno ví"],
"A needle in a haystack":["jehla v kupce sena"],
"A nervous wreck":["uzlíček nervů;nervák"],
"A penny for your thoughts": ["Řekni mi, co si myslíš"],
"A penny saved is a penny earned": ["Co ušetřím, nemusím vydělat"],
"A perfect storm": ["Horší to už být nemohlo"],
"A picture is worth 1000 words": ["Jeden obrázek řekne víc než tisíc slov"],
"A safe bet":["sázka na jistotu;tutovka"],
"A snowball effect": ["Efekt sněhové koule"],
"A snowball's chance in hell": ["Naprosto bez šance"],
"A stitch in time saves nine": ["Problémy je nejlepší řešit včas"],
"A storm in a teacup":["bouře ve sklenici vody"],
"Accidents will happen":["nehody se stávají; měli byste počítat se vším"],
"Accidents will happen.":["Nehody se stávají. Měli byste počítat se vším."],
"Actions speak louder than words": ["Skutky jsou víc než slova"],
"Add insult to injury": ["Celé to ještě víc zhoršit"],
"All good things must come to an end.":["Všechno dobré jednou končí."],
"All talk, no action.":["Skutek utek."],
"An apple a day keeps the doctor away": ["jablka jsou zdravá"],
"An ounce of prevention is worth a pound of cure": ["Prevence je základ"],
"Another cup of tea":["jiná věc; mimo téma"],
"Answer the door!": ["jděte otevřít dveře!"],
"Ants in pants":["mít roupy / neposedět"],
"Ants in pants.": ["Mít roupy. / Neposedět."],
"Are you finished?":["Už jsi skončil?"],
"Are you serious":["myslíte to vážně"],
"As a matter of fact / in the matter of fact":["ve skutečnosti, vlastně I've got it"],
"As like as two peas":["v doslovném překladu než dvě fazole, v přeneseném podobný jako vejce vejci"],
"As right as rain":["Dokonalost sama"],
"As soon as you can":["co nejdříve, jak nejdříve budeš moci"],
"As sure as eggs are eggs.":["Tak jako, že se xxx jmenuju."],
"Ask for the moon":["požadovat nemožné"],
"At the end of the day":["na konec; ve výsledku"],
"At what time":["v kolik hodin"],
"Attention":["pozor"],
"Awesome":["úžasné, dělo"],
"Bad form":["nezdvořilý"],
"Bag of bones":["kost a kůže, hodně hubený"],
"Bag of nerves":["uzlíček nervů; nervák"],
"Bark up the wrong tree":["plakat na špatném hrobě"],
"Bark up the wrong tree.": ["Plakat na špatném hrobě."],
"Barking up the wrong tree":["Plakat na špatném hrobě"],
"Be (a) chicken":["být strašpytel"],
"Be a lemon":["Je to krám.; Je to k ničemu."],
"Be a pain in the neck":["jít někomu na nervy"],
"Be a turkey":["být hloupý"],
"Be as cool as a cucumber":["chladnokrevný; nic ho nerozhází"],
"Be in a jack":["být v průšvihu"],
"Be more considerate!":["trochu víc uvažuj !"],
"Be off at once":["koukejte zmizet!"],
"Be out of the question":["vyloučeno; nepřichází v úvahu"],
"Be that as it may":["ať je tomu jakkoliv"],
"Beat about the bush.":["Chodit okolo horké kaše."],
"Beat around the bush":["Chodit kolem horké kaše"],
"Beating a dead horse.":["Házet na stěnu hrách. Házet perly sviním."],
"Better buy":["nebo totéž"],
"Better late than never":["Lépe pozdě než vůbec"],
"Better safe than sorry.":["Opatrnosti nikdy nezbývá. Dvakrát měř a jednou řež."],
"Big fish":["tedy velká ryba, se používá k označení důležité osoby"],
"Bill":["William"],
"Birds of a feather flock together":["Vrána k vráně sedá (obvykle negativně)"],
"Bite off more than you can chew":["Vzít si příliš velké sousto"],
"Bite the bullet":["Kousnout do kyselého jablka (muset udělat něco nepříjemného)"],
"Bite your tongue.": ["Držet jazyk za zuby."],
"Bolt from the blue":["Blesk z čistého nebe"],
"Booze":["alkohol, chlast"],
"Break a leg!":["Zlom vaz! Hodně štěstí!"],
"Break a leg":["Zlom vaz"],
"Break the ice":["Prolomit ledy, napětí mezi lidmi"],
"Bucks":["peníze, prachy"],
"Bullshit":["hloupost, blbost"],
"Burn bridges":["Pálit za sebou mosty"],
"Burn one's bridges behind one":["pálit za sebou mosty"],
"Bury the past":["udělat tlustou čáru za minulostí;začít znova"],
"Business, you know":["to víte, obchod"],
"Butter wouldn't melt in her mouth":["vypadá jako neviňátko"],
"Butterflies in your stomach":["někdo je kvůli něčemu nervózní; běhají po něm mravenci"],
"By the skin of your teeth":["O vlásek, jen tak tak"],
"By the way":["mimochodem"],
"Call it a day":["Zapíchnout to, zabalit to (skončit práci)"],
"Calm before the storm":["Ticho před bouří"],
"Can you beat it?":["Dokážete to překonat ? / hovor."],
"Can you fix it":["umíte to spravit?"],
"Chicken out":["zbaběle vycouvat"],
"Chicken":["zbabělec"],
"Come along with me and have a drink":["pojď se se mnou něčeho napít"],
"Come rain or shine":["I kdyby trakaře padaly"],
"Come right in":["jen pojďte dál"],
"Come, come Lady Astor":["ale, ale lejdy Astorová"],
"Comparing apples to oranges":["Srovnávat hrušky s jablky"],
"Copycat":["napodobenina / opičící se papoušek"],
"Costs an arm and a leg":["Stát fůru peněz"],
"Could you show me?":["Mohli byste mi to ukázat?"],
"Cry me a river.": ["Klidně se snaž, ale moje sympatie nedostaneš."],
"Cry wolf.": ["Vyvolávat planý poplach."],
"Curiosity killed the cat":["Kdo se moc ptá, moc se dozví"],
"Cut somebody some slack":["Nebýt k někomu tak kritický, být shovívavější"],
"Cut the crap!":["Neříkej nesmysly!"],
"Cut the mustard":["Podat očekávaný výkon (udělat to správně)"],
"Cutting corners":["Něco odbýt, odfláknout"],
"Dead as a doornail.": ["Nepoužitelný."],
"Dear Mr.":["Vážený pane / oslovení v úvodu dopisu"],
"Dear me":["to mne podržte!"],
"Decline and fall":["vzestup a pád"],
"Detour":["objížďka"],
"Did you enjoy the meals":["chutnalo Vám?"],
"Did you read that ad /advertisement/":["četl jsi ten inzerát?"],
"Do something at the drop of a hat":["Okamžitě, bez rozmýšlení něco udělat"],
"Do unto others as you would have them do unto you":["Nedělej druhým, co nechceš, aby dělali tobě. Známé rovněž jako 'The Golden Rule'"],
"Do you mind":["máte něco proti tomu /odpovíte-li yes, znamená to, že máte námitky"],
"Do you remember something in particular":["vzpomínáte si na něco zvláštního"],
"Do you smoke?":["Kouříte?"],
"Dog's life":["psí život"],
"Don't beat a dead horse":["Házet hrách na zeď, zbytečně se snažit"],
"Don't count your chickens before they hatch":["Neříkej hop..."],
"Don't cry over spilt milk":["Naříkat nad rozlitým mlékem"],
"Don't get me wrong.":["Nechápej mě špatně."],
"Don't give up your day job":["Tohle není zrovna tvoje parketa (=moc ti to nejde)"],
"Don't judge a book by its cover.":["Nesuď knihu podle obalu."],
"Don't put all your eggs in one basket":["Nesázej všechno na jednu kartu (=příliš riskuješ)"],
"Don't put all your eggs in one basket.":["Nesázej na jednoho koně. Nevsázej vše na jednu kartu."],
"Dorky":["hlupák, hňup"],
"Down to the wire.": ["Za 5 minut 12."],
"Dry run":["nanečisto"],
"Eager beaver":["horlivec"],
"Early bird catches the worm.": ["Ranní ptáče dál doskáče."],
"Early bird":["ranní ptáče"],
"Easy does it":["Opatrně! Pomalu!"],
"Every cloud has a silver lining":["Všechno zlé je k něčemu dobré"],
"Every dog has his day":["Na každého se jednou dostane (=každý má aspoň jednu šanci)"],
"Every man is the architect of his own fortune.":["Každý svého štěstí strůjce."],
"Every rose has its thorn.":["Každá růže má svůj trn."],
"Face the music.": ["Převzít zodpovědnost za činy."],
"Face up to a failure":["smířit se s porážkou"],
"Familiarity breeds contempt":["Znát někoho až příliš dobře (tj. i jeho špatné vlastnosti)"],
"Feel something in one's bones":["cítit to v kostech"],
"Fishy":["divný;podezřelý"],
"Fit as a fiddle":["Zdravý jako rybička"],
"For God’s sake":["Panebože! Proboha!"],
"Fortune favours the bold":["Odvážnému štěstí přeje"],
"Get a second wind":["Nabrat čerstvý vítr do plachet"],
"Get a taste of your own medicine":["Chovat se k někomu tak, jak se k druhým chová on – aby si zkusil, jaké to je (negat.)"],
"Get ahead":["dělat kariéru"],
"Get hold of the wrong end of the stick":["vzít věc za špatný konec"],
"Get out of hand":["Vymknout se z rukou"],
"Get something out of your system":["Udělat něco, co mám už nějakou dobu v plánu – abych se mohl posunout dál"],
"Get wind of something":["Dozvědět se, doslechnout se (něco tajného)"],
"Get your act together":["Buď to dělej pořádně, nebo toho radši nech"],
"Give me a hand please!":["Pomoz mi prosím!"],
"Give rein":["nechat volnou ruku"],
"Give someone the benefit of the doubt":["Věřit někomu něco"],
"Give someone the cold shoulder":["Někoho záměrně ignorovat"],
"Go back to the drawing board":["A zpátky na start... musíme začít zase od začátku"],
"Go down in flames":["Vyhořet na něčem (=neuspět)"],
"Go on a wild goose chase":["Marná snaha, nic než ztráta času"],
"Good things come to those who wait":["Trpělivost růže přináší"],
"Hang in there":["Nevzdávej to"],
"Has the cat got your tongue?":["Došli ti slova? Oněměl jsi?"],
"Haste makes waste":["Spěch je špatný rádce"],
"Have a bee in one's bonnet":["mít brouka v hlavě"],
"Have ants in one's pants":["mít roupy;být neposedný"],
"Have the guts":["mít odvahu"],
"Have your head in the clouds":["Nesoustředit se, být duchem mimo"],
"He has bigger fish to fry":["Takovéhle věci on neřeší. Má jiné (větší) starosti"],
"He who laughs last laughs loudest":["Kdo se směje naposled, ten se směje nejlíp"],
"He's a chip off the old block":["Jablko nepadá daleko od stromu"],
"He's not playing with a full deck":["Je to trouba"],
"He's off his rocker":["Zbláznil se (=chová se velmi podivně)"],
"He's sitting on the fence":["Nedokáže se rozhoupat (=rozhodnout)"],
"Hear something straight from the horse's mouth":["Mít něco (nějakou informaci) přímo od zdroje"],
"Heaven on earth":["ráj na zemi"],
"Hit the nail on the head":["Uhodit hřebíček na hlavičku"],
"Hit the nail on the head.":["Uhodit hřebík na hlavičku."],
"Hit the sack":["Jít na kutě, zapadnout do postele"],
"Hold your horses!": ["Brzdi, Nežeň, Neukvapuj se! Zadrž!"],
"Holy cow!":["Ty jo!"],
"How about you?":["A co ty?"],
"How was the movie?":["Jaký byl film?"],
"Hunger is the best sauce.":["Hlad je nejlepší kuchař."],
"I am full":["Jsem plný"],
"I am going to ...":["mám v úmyslu, hodlám /viz. faleš. budoucí čas/"],
"I am going to":["hodlám /něco udělat, tzv. falešný budoucí čas/"],
"I am hungry as a horse":["mám hlad jako vlk"],
"I am in a hurry":["jsem ve spěchu, pospíchám"],
"I am not very well":["moc dobře se mi nevede"],
"I am on a diet":["držím dietu"],
"I am short of /out of/ money":["nemám dost peněz"],
"I am sick of everything":["mám všeho dost /po krk/"],
"I am sorry for you":["lituji Vás"],
"I am sorry":["lituji, je mi líto"],
"I am sorry, really I am":["je mi líto, opravdu líto"],
"I am sory to say":["lituji, že musím říci..."],
"I am sure you are right":["jistě (jsem si jist, že...), máte pravdu"],
"I am sure":["jsem si jist, určitě"],
"I am thhrough with it":["už jsem s tím skoncoval"],
"I am through with you":["už jsem s Vámi skoncoval"],
"I am to see Mr. XY.":["přišel jsem navštívit pana XY."],
"I am very busy":["mám hrozně moc práce"],
"I am wondering":["1. rád bych věděl, 2. to se divím, 3. to mi leží v hlavě"],
"I beg to request":["dovoluji si požádat"],
"I beg your pardon":["prosím?"],
"I can't get it started":["nemohu to nastartovat"],
"I changed my mind":["rozmyslel jsem si to"],
"I don't know what to do first":["nevím co dříve dělat"],
"I don't think so":["myslím, že ne"],
"I doubt it":["o tom pochybuji, to se mi nezdá"],
"I have no fancy for":["neoblibuji ..."],
"I haven't got any money left":["nezbyly mi žádné peníze"],
"I haven't seen you for ages":["neviděl jsem Vás hrozně dlouho"],
"I like you":["Mám tě rád"],
"I mean it!":["Myslím to vážně."],
"I must be going":["musím jít"],
"I must go for shopping":["musím jít nakupovat"],
"I remain yours very sincerely":["zůstávám v upřímné úctě /fráze v dopise/"],
"I shall manage myself":["zařídím to sám"],
"I shall think it over":["budu o tom přemýšlet, rozmyslím si to"],
"I want as well":["Chci také"],
"I want you to have a good look around":["ale, aby se dobře rozhlédl"],
"I wasn't born yesterday.":["nejsem včerejší"],
"I will pick you up":["Vyzvednu tě"],
"I wish I were you":["rád bych byl na Vašem místě Not really?"],
"I wish to inform you":["dovoluji si Vás informovat"],
"I won't be long / I will not":["nebudu tam dlouho"],
"I wonder who that can be":["to b...i přejete!"],
"I wonder":["1. divím se"],
"Ignorance is bliss":["Nejlepší je nic nevědět"],
"Is it drinkable water?":["Je to pitná voda?"],
"It ain't over till the fat lady sings":["Ještě není konec, ještě se uvidí"],
"It cost me an arm and a leg":["peněz jak za kozu"],
"It doesn't make any difference.":["Nehraje to žádnou roli."],
"It doesn't ring a bell.":["To mi nic neříká."],
"It is a poor workman who blames his tools":["Svádět vlastní neschopnost na někoho/něco jiného"],
"It is always darkest before the dawn":["Nakonec se všechno v dobré obrátí; zase bude líp"],
"It takes one to know one":["Nejsi o nic lepší než já"],
"It takes two to tango":["Svůj podíl na tom mají oba"],
"It ́s not good crying over spilt milk.":["Neplač nad rozlitým mlékem."],
"It's a piece of cake":["Je to brnkačka (to se dá zvládnout levou zadní)"],
"It's a storm in teacup.": ["Z toho mráčku nezaprší."],
"It's about as broad as it's long":["to je jako prašť a uhoď"],
"It's all Greek tome.":["Je to pro mě španělská vesnice."],
"It's always darkest before the dawn.":["Nic není tak zlé, jak to vypadá."],
"It's my turn.":["Jsem na řadě."],
"It's none of your business.":["Do toho tě nic není."],
"It's not my cup of tea.":["Není to můj šálek kávy."],
"It's not rocket science":["Není to žádná věda"],
"It's raining cats and dogs":["Lije jako z konve"],
"It's raining cats and dogs.":["padají trakaře; žení se všichni čerti"],
"It’s a mixed blessing":["má to svá plus i mínus"],
"Jump on the bandwagon":["Dělat něco, protože je to právě v módě"],
"Keep left":["držte se vlevo"],
"Keep right":["držte se vpravo"],
"Keep to the right":["držte se vpravo"],
"Keep trying":["stále se pokoušej"],
"Kill two birds with one stone":["Zabít dvě mouchy jednou ranou"],
"Kill two birds with one stone.":["Zabít dvě mouchy jednou ranou."],
"Know which way the wind is blowing":["Vědět, odkud vítr vane (obvykle míněno negativně)"],
"Lame":["trapné, suché"],
"Last straw":["poslední kapka"],
"Leave no stone unturned":["Obrátit všechno vzhůru nohama (=dívat se po něčem všude)"],
"Leave no stone unturned.":["Nenechat kámen na kameni."],
"Let me have some lines":["pošli mi /napiš mi/ pár řádků"],
"Let me know":["dejte mi vědět"],
"Let me see":["počkejte, počkejte"],
"Let sleeping dogs lie":["Nepíchat do vosího hnízda"],
"Let sleeping dogs lie.":["Nedráždi hada bosou nohou."],
"Let someone off the hook":["Sejmout z někoho zodpovědnost"],
"Let the cat out of the bag":["Prozradit tajemství"],
"Let us go / let's go!":["pojd'me"],
"Let's get started":["Tak začneme ne?"],
"Let's have it":["tak ven s tím"],
"Life is not a bowl of cherries.":["Život není procházka růžovým sadem."],
"Like a bolt from the blue":["jako blesk z čistého nebe"],
"Like riding a bicycle":["Něco, co se člověk naučí a už nikdy nezapomene"],
"Like two peas in a pod":["Nerozlučná dvojka"],
"Live and learn":["Člověk se pořád učí (=udělal jsem chybu)"],
"Live in clover":["žít jako v bavlnce"],
"Loaded":["bohatý, zazobaný"],
"Look at me":["podívejte se na mne"],
"Look before you leap":["Dvakrát měř, jednou řež"],
"Look here Mom":["podívej se mami.."],
"Look here":["podívejte, hleďte, hele, pohleďte (zdvořilé \"hele\")"],
"Look out":["pozor"],
"Lose heart":["ztrácet odvahu"],
"Lower one's sights":["slevit z nároků"],
"Make a beeline":["namířit si to přímo (vzdušnou čarou)"],
"Make a long story short":["Abych to zkrátil..."],
"Make a mountain out of a molehill.":["Dělat z komára velblouda."],
"Make hay while the sun shines":["Kout železo, dokud je žhavé"],
"Make it forty dollars":["doslova : udělejte to na 40 dolarů"],
"Make one‘s day":["udělat někoho šťastným"],
"Make up your mind":["rozhodněte se"],
"Make yourself comfortable":["udělejte si pohodlí"],
"Maximum speed 55 miles":["max. rychlost 88 km"],
"Mind what you're saying":["dejte si pozor na to, co říkáte"],
"Mind your own business":["Starej se o své. Hleď si svého."],
"Minimum speed 40 miles":["nejmenší rychlost 64 km"],
"Miss the boat":["Propásnout něco"],
"Mr. X. reporting Sir":["hlásí se pan iks pane"],
"Mr. X. to see you":["pan iks přišel, aby Vás navštívil a podobně"],
"My Goodness":["ty má dobroto, proboha"],
"My hairs standing on end":["vlasy hrůzou stávají na hlavě"],
"My time is up":["můj čas vypršel"],
"Never say never.":["Nikdy neříkej nikdy."],
"No U turn":["zákaz otáčení"],
"No matter whether...":["bez ohledu na to zda..."],
"No pain, no gain":["Bez práce nejsou koláče"],
"No pain, no gain.":["Bez práce nejsou koláče. / Žádná bolest, žádný zisk."],
"Nobody cares two hoots about it.":["Po tom ani pes neštěkne."],
"Not for all the tea in China.":["Ani za nic na světě."],
"Not to have anything between the ears":["být hloupý"],
"Nothing doing":["/slang/ ne, to nepřichází v úvahu, to nejde"],
"Nothing like that":["nic takového"],
"Nothing ventured, nothing gained":["risk je zisk"],
"Offering you again our apology":["znovu se Vám omlouvajíce"],
"Oh I see!":["aha"],
"Oh my gosh!":["jemináčku!"],
"Oh please do!":["jenom, prosím Vás, to udělejte"],
"On cloud nine":["V sedmém nebi"],
"On second thought":["když ale tak o tom přemýšlím, napadá mne, když jsem o tom znovu přemýšlel, při správné myšlence"],
"On the ball":["Dělat něco dobře"],
"On the dot":["dochvilný; na minutu přesný"],
"On thin ice":["Na tenkém ledě"],
"On this occasion":["při této příležitosti"],
"Once bitten, twice shy":["Kdo se jednou spálí..."],
"Once in a blue moon":["Jednou za uherský rok"],
"Once upon a time there was ...":["byl jednou jeden"],
"One by one":["jedno po druhém"],
"Out of the frying pan and into the fire":["Z deště pod okap"],
"Pigheaded":["tvrdohlavý"],
"Play devil's advocate":["Dělat ďáblova advokáta"],
"Please sit down and join us":["prosím posaďte se a připojte se k nám"],
"Please":["prosím! neodpovídá se na fenk jů"],
"Promise the moon":["slíbit modré z nebe"],
"Pull someone's leg":["Utahovat si z někoho, vodit ho za nos"],
"Pull yourself together":["Zklidni se, hoď se do klidu"],
"Put it in a nutshell":["jednoduše řečeno; v kostce"],
"Put something on ice":["Dát nějakou věc k ledu (odložit)"],
"Put the cart before the horse.":["Stavět dům bez střechy."],
"Rain on someone's parade":["Zkazit někomu něco"],
"Relieve one's feelings":["nechat průchod citům"],
"Rest on one's laurels":["usnout na vavřínech"],
"Rookie":["začátečník, zelenáč"],
"Round the bend":["nemít všech pět pohromadě"],
"Run like the wind":["Běžet jak s větrem o závod"],
"Saving for a rainy day":["Schovat něco pro strýčka Příhodu"],
"Shake like leaf":["třást se jako osika"],
"Shame on you!":["Styď se!"],
"Shape up or ship out":["Dělej to pořádně, nebo to nech být"],
"Sing a different song":["změnit názor"],
"Sink or swim.":["Buď, anebo. Hop nebo trop."],
"Slow and steady wins the race":["Spolehlivost je víc než rychlost"],
"Snowed under":["Zavalený (prací)"],
"So far so good":["Zatím se to vyvíjí dobře"],
"Speak of the devil":["My o vlku..."],
"Spill the beans":["Vyklopit něco (=prozradit tajemství)"],
"Take a rain check":["Odložit něco na později"],
"Take forty winks":["Dát si dvacet."],
"Take it with a grain of salt":["Brát něco se špetkou soli"],
"Take the reins":["převzít vedení"],
"Takes one to know one.":["Ty máš co říkat. / Kdo to říká, ten to je."],
"Taste your own medicine.":["Spadnout do vlastní jámy."],
"That ship has sailed":["Pozdě honit bycha"],
"That's a different kettle of fish.":["To je něco jiného. / To je jiná káva."],
"That's a good idea.":["To je dobrý nápad."],
"That's about the limit.":["To je totální nestydatost."],
"That's the last straw":["Už toho mám dost, ztratil jsem trpělivost"],
"That’s not my cup of tea":["to není můj šálek čaje; to není nic pro mě"],
"The apple of discort":["kámen úrazu"],
"The appleof discort":["kámen úrazu"],
"The back of beyond":["zapadákov"],
"The ball is in your court":["Míč je teď na tvé straně"],
"The best of both worlds":["Ideální situace, nejlepší varianta"],
"The best thing since sliced bread":["Geniální vynález"],
"The common knowledge":["všeobecné znalosti"],
"The devil is in the details":["Ďábel tkví v detailech"],
"The early bird gets the worm":["Ranní ptáče dál doskáče"],
"The elephant in the room":["Problém, o kterém nikdo nechce mluvit"],
"The lion's share":["největší podíl"],
"The moment of truth":["okamžik pravdy"],
"The pot calling the kettle black":["Kritizovat někoho a přitom nebýt o nic lepší"],
"The rat race":["pachtění se za penězi"],
"The whole nine yards":["Celou cestu/dobu; všechno"],
"There are clouds on the horizon":["Z toho kouká malér"],
"There are other fish in the sea":["Tohle určitě není poslední příležitost"],
"There's a method to his madness":["Vypadá jako blázen, ale to je jenom zdání"],
"There's no such thing as a free lunch":["Nic není nikdy zadarmo"],
"Things are going from bad to worse.":["Jde to od desíti k pěti."],
"Those who live in glass houses shouldn't throw stones":["Kdo má máslo na hlavě..."],
"Through thick and thin":["Kamarád 'do deště'"],
"Throw caution to the wind":["Zariskovat"],
"Time flies when you're having fun":["Zapomenout na čas (když se člověk dobře baví, nevnímá, jak rychle čas běží)"],
"Time is money":["Čas jsou peníze"],
"Time's up!":["Čas vypršel."],
"To be a lemon":["je to krám; je to k ničemu(většinou o přístroji, stroji)"],
"To be a peach":["být velmi příjemný"],
"To be a piece of cake":["být snadné; to je hračka"],
"To be a rat":["být krysa; špatný člověk; dělat podrazy"],
"To be a smart cookie":["být bystrý,pohotový"],
"To be a turkey":["být hloupý, natvrdlý"],
"To be as cool as a cucumber":["studený jako ryba; nic ho nerozhází; chladnokrevný"],
"To be chicken":["bát se; být vystrašený"],
"To be foxy":["být přitažlivý"],
"To be hot-headed":["být horkokrevný; horká hlava; výbušný; rychle se rozzlobit"],
"To be hot-headed. ":["Být horká hlava."],
"To be in the black":["být solventní; mít dost peněz na zaplacení všech závazků"],
"To be in the pink":["být krev a mléko"],
"To be in the red":["mít dluhy; nebýt solventní"],
"To be the top banana":["být nejdůležitější osobou z nějaké skupiny (hlavně vpráci)"],
"To be the top banana.": ["Být nejdůležitější osoba ze skupiny."],
"To be white as a sheet":["být bílý jako křída"],
"To be yellow":["bát se"],
"To bite your tongue":["držet jazyk za zuby"],
"To bring home the bacon":["vydělávat na chleba, na živobytí"],
"To bring home the bacon.": ["Vydělávat na chleba / živobytí."],
"To cry over splilled milk":["plakat na rozlitým mlékem"],
"To eat like a bird":["jíst jako vrabec; jíst málo"],
"To eat like a horse":["jíst hodně"],
"To eat like a pig":["neumět se chovat u stolu; jíst jako prase"],
"To feel blue":["mít deprese"],
"To feel blue.": ["Mít deprese."],
"To feel something in one's bones.": ["Cítit to v kostech."],
"To get bent out of shape":["Naštvat se"],
"To get the chop":["být propuštěn"],
"To go the dogs.":["Jít od desíti k pěti."],
"To have a lot on one's plate":["mít toho příliš mnoho 'na talíři', pouštět se do hodně věcí"],
"To have goose pimples/bumps.":["Mít husí kůži. Opupínkovat se."],
"To have heart in mouth.": ["Být extrémně vyděšený."],
"To have one's fingers in many pies":["dělat mnoho různých věcí najednou"],
"To hold one's tongue":["držet jazyk za zuby"],
"To keep in the dark":["někomu něco zatajit"],
"To kick the bucket":["zaklepat bačkorami; zemřít"],
"To kick the bucket.": ["Zemřít."],
"To knock your soft off":["vyrazit dech"],
"To lead someone by the nose":["vodit někoho za nos"],
"To lend someone an ear":["poslouchat někoho"],
"To lend someone an ear.": ["Naslouchat někomu."],
"To lose heart.": ["Ztratit odvahu."],
"To make a mountain out of a molehill.": ["Dělat z komára velblouda."],
"To make matters worse":["Zhoršit nějaký problém"],
"To promise the Moon.": ["Slibem nezarmoutíš."],
"To pull one's leg":["táhnout někoho za nos, natahovat"],
"To push up daisies":["být po smrti"],
"To push up daisies.": ["Být po smrti."],
"To see red":["vidět rudě; být rozzuřený"],
"To sell like hot cakes":["jít na dračku"],
"To sell like hot cakes.": ["Jde to na dračku."],
"To spill the beans":["vykecat něco, prozradit tajemství"],
"To walk on eggshells":["chodit kolem po špičkách; velice opatrně"],
"To walk on eggshells.": ["Chodit okolo po špičkách / opatrně."],
"To wear your heart on your sleeve":["mít srdce na dlani"],
"To wear your heart on your sleeve.": ["Mít srdce na dlani."],
"To work like adog":["dřít jako kůň"],
"Under the weather":["Nebýt ve své kůži"],
"Walk on eggshells":["chodit kolem po špičkách; velice opatrně"],
"Waste not, want not":["Když nebudeš plýtvat, budeš mít vždycky dost"],
"We see eye to eye":["V tom jsme zajedno"],
"We'll cross that bridge when we come to it":["Nač stahovat kalhoty, brod je ještě daleko"],
"Wear your heart on your sleeve":["mít srdce na dlani"],
"Weather the storm":["Vyčkat, až se to přežene / procházet něčím těžkým"],
"Well begun is half done":["Dobře začít je půl úspěchu"],
"Well done steak":["propečený biftek medium done"],
"What a shame":["jaká škoda"],
"What about ...":["a co ..."],
"What about me":["a co já?, nebo: a co pro mne?"],
"What about you?":["no a co Vy,"],
"What can I do for you":["co mohu pro Vás udělat, čím mohu sloužit"],
"What do I do with it":["What am I to do with it"],
"What do you do":["co děláte?"],
"What do you make of it?":["co z toho usuzujete?"],
"What is the time?":["kolik je hodin?"],
"What of it":["no a co z toho"],
"What was on?":["co se dělo nebo co se hrálo?"],
"What was the matter":["co se stalo"],
"What was wrong with it?":["co s tím bylo?"],
"What will the people think about us":["co si o nás lidi pomyslí"],
"What will you have":["co si dáte? co račte poroučet?"],
"What's happened":["co se stalo"],
"What's his phone number":["jaké má telefonní číslo"],
"What's on your mind":["co máte na mysli"],
"What's that?":["co to?"],
"What's the big idea":["co je to za nápad"],
"What's up":["co je?"],
"What's up?":["Co se děje? Jak se máš?"],
"What's use of":["jaký má smysl..."],
"When it rains it pours":["Když se daří, tak se daří... (=když se všechno pokazí naráz)"],
"Where are you from?":["Odkud jste?"],
"Where can I withdraw money?":["Kde si mohu vybrat peníze?"],
"Where would you like to go?":["Kam bys chtěla jít?"],
"Which is the way":["kudy se jde...?"],
"Who is starring?":["kdo hraje hlavní roli?"],
"Will that be of any help to you?":["pomůže Vám to?"],
"Wolf in sheep's clothing.": ["Potvora převlečená za kamaráda."],
"Work like a dog":["dřít jako kůň"],
"Work upon":["razit si cestu vzhůru"],
"Wrap your head around something":["Přijít něčemu na kloub"],
"You are my only friend":["ty jsi mým jediným přítelem / přítelkyní"],
"You are right / As for the ...":["máte pravdu "],
"You are right to do so":["máš právo se tak chovat"],
"You are right to do so.":["Máš právo se tak chovat."],
"You are shadowed":["jste sledován, / stopován"],
"You are telling me":["mně to budete povídat ..."],
"You bet":["to se vsaď"],
"You can catch more flies with honey than you can with vinegar":["Slušnost všude otevírá dveře"],
"You can lead a horse to water, but you can't make him drink":["Navést ho můžeš, ale rozhodnout se už musí sám"],
"You can say that again":["To máš recht"],
"You can't have your cake and eat it too":["Člověk nemůže mít všechno"],
"You can't have your cake and eat it.":["Nemůžeš mít všechno. / chtít, aby se vlk nažral a koza zůstala celá."],
"You can't judge a book by its cover":["Nesuď podle zevnějšku"],
"You can't make an omelet without breaking some eggs":["Každá legrace něco stojí; nic není zadarmo"],
"You don't have to be !":["nemusíte /být/"],
"You know what they say.":["Víš, co se říká."],
"You knowwhat they say.":["Víš, co se říká."],
"You may leave now to carry on your duty":["můžete teď odejít, pokračovat ve službě"],
"You'll laugh on the other side of your face.":["On tě ten smích přejde."],
"You're barking up the wrong tree.":["Pláčeš na špatném hrobě."],
"You're kidding":["/slang/ Vy žertujete, děláte si legraci, srandu"],
"You're welcome":["jste vítán"],
"Your guess is as good as mine":["Nemám ponětí"],
"Your letter in hand":["obdrželi jsme Váš dopis"],
"keep the change":["nechte si drobné (od cesty)"],
"not at all":["není zač"],
"what is it":["co je to ( hovorově: Co je? Co máš nového?)"],
}