var slovnik={
"Answer the door!":["jděte otevřít dveře!"],
"Are you serious":["myslíte to vážně"],
"As a matter of fact /také : in the matter of fact/":["ve skutečnosti, vlastně I've got it"],
"As soon as you can":["co nejdříve, jak nejdříve budeš moci"],
"At what time":["v kolik hodin"],
"Attention":["pozor"],
"Be more considerate!":["trochu víc uvažuj !"],
"Be off at once":["koukejte zmizet!"],
"Be that as it may":["ať je tomu jakkoliv"],
"Better buy":["nebo totéž"],
"Bill":["William"],
"Business, you know":["to víte, obchod"],
"By the way":["mimochodem"],
"Can you beat it?":["/hovor./"],
"Can you fix it":["umíte to spravit?"],
"Come along with me and have a drink":["pojď se se mnou něčeho napít"],
"Come right in":["jen pojďte dál"],
"Come, come Lady Astor":["ale, ale Lady Astorová"],
"Dear me":["to mne podržte!"],
"Dear Mr.":["Vážený pane /oslovení v úvodu dopisu/"],
"Detour":["objížďka"],
"Did you enjoy the meals":["chutnalo Vám?"],
"Did you read that ad /advertisement/":["četl jsi ten inzerát?"],
"Do you mind":["máte něco proti tomu /odpovíte-li \"yes\", znamená to, že máte námitky"],
"Do you remember something in particular":["vzpomínáte si na něco zvláštního"],
"I am going to":["hodlám /něco udělat, tzv. falešný budoucí čas/"],
"I am going to ...":["mám v úmyslu, hodlám /viz. faleš. budoucí čas/"],
"I am hungry as a horse":["mám hlad jako vlk"],
"I am in a hurry":["jsem ve spěchu, pospíchám"],
"I am in a hurry":["pospíchám"],
"I am not very well":["moc dobře se mi nevede"],
"I am on a diet":["držím dietu"],
"I am short of /out of/ money":["nemám dost peněz"],
"I am sick of everything":["mám všeho dost /po krk/"],
"I am sorry":["lituji, je mi líto"],
"I am sorry for you":["lituji Vás"],
"I am sorry, really I am":["je mi líto, opravdu líto"],
"I am sory to say":["lituji, že musím říci..."],
"I am sure":["jsem si jist, určitě"],
"I am sure you are right":["jistě (jsem si jist, že...), máte pravdu"],
"I am thhrough with it":["už jsem s tím skoncoval"],
"I am through with you":["už jsem s Vámi skoncoval"],
"I am to see Mr. XY.":["přišel jsem navštívit pana XY."],
"I am very busy":["mám hrozně moc práce"],
"I am wondering":["1. rád bych věděl, 2. to se divím, 3. to mi leží v hlavě"],
"I beg to request":["dovoluji si požádat"],
"I beg your pardon":["prosím?"],
"I can't get it started":["nemohu to nastartovat"],
"I don't know what to do first":["nevím co dříve dělat"],
"I don't think so":["myslím, že ne"],
"I don't think so":["myslím, že ne"],
"I doubt it":["o tom pochybuji, to se mi nezdá"],
"I have no fancy for":["neoblibuji ..."],
"I haven't got any money left":["nezbyly mi žádné peníze"],
"I haven't seen you for ages":["neviděl jsem Vás hrozně dlouho"],
"I changed my mind":["rozmyslel jsem si to"],
"I changed my mind":["rozmyslel jsem si to"],
"I must be going":["musím jít"],
"I must be going":["musím jít"],
"I must go for shopping":["musím jít nakupovat"],
"I remain yours very sincerely":["zůstávám v upřímné úctě /běžná fráze v dopise/"],
"I shall manage myself":["zařídím to sám"],
"I shall think it over":["budu o tom přemýšlet, rozmyslím si to"],
"I want you to have a good look around":["ale, aby se dobře rozhlédl"],
"I wish I were you":["rád bych byl na Vašem místě Not really?"],
"I wish to inform you":["dovoluji si Vás informovat"],
"I won't be long /I will not/":["nebudu tam dlouho"],
"I wonder":["1. divím se"],
"I wonder who that can be":["to b...i přejete!"],
"Keep left":["držte se vlevo"],
"Keep right":["držte se vpravo"],
"keep the change":["nechte si drobné (od cesty)"],
"Keep to the right":["držte se vpravo"],
"Keep trying":["stále se pokoušej"],
"Let me have some lines":["pošli mi /napiš mi/ pár řádků"],
"Let me know":["dejte mi vědět"],
"Let me see":["počkejte, počkejte"],
"Let us go /zkráceně: let's go!/":["pojd'me"],
"Let's get started":["Tak začneme ne?"],
"Let's have it":["tak ven s tím"],
"Look at me":["podívejte se na mne"],
"Look here":["podívejte, hleďte, hele"],
"Look here":["hleďte, pohleďte (takové zdvořilé \"hele\")"],
"Look here Mom":["podívej se mami.."],
"Look out":["pozor"],
"Make it forty dollars":["doslova : udělejte to na 40 dolarů"],
"Make up your mind":["rozhodněte se"],
"Make yourself comfortable":["udělejte si pohodlí"],
"Maximum speed 55 miles":["max. rychlost 88 km"],
"Mind what you're saying":["dejte si pozor na to, co říkáte"],
"Mind your own business":["hleďte si svého"],
"Minimum speed 40 miles":["nejmenší rychlost 64 km"],
"Mr. X. reporting Sir":["hlásí se pan X.pane"],
"Mr. X. to see you":["pan X. přišel, aby Vás navštívil a podobně"],
"Mrs.":["Missis /misiz/"],
"My Goodness":["ty má dobroto, proboha"],
"My time is up":["můj čas vypršel /ostatní obraty jsou již zcela běžné a zcela nepohádkové/."],
"No matter whether...":["bez ohledu na to zda..."],
"No U turn":["zákaz otáčení"],
"not at all":["není zač"],
"Nothing doing /slang/":["ne, to nepřichází v úvahu, to nejde"],
"Nothing like that":["nic takového"],
"Offering you again our apology":["znovu se Vám omlouvajíce"],
"Oh I see!":["aha"],
"Oh my gosh!":["jemináčku!"],
"Oh please do!":["jenom, prosím Vás, to udělejte"],
"On second thought":["když ale tak o tom přemýšlím, napadá mne"],
"On second thought":["když jsem o tom znovu přemýšlel, při správné myšlence"],
"On this occasion":["při této příležitosti"],
"Once upon a time there was ... Obrat vyskytující se hlavně v pohádkách":["znamená naše \"byl jednou jeden atd.\""],
"One by one":["jedno po druhém"],
"Please":["prosím!nikdy se tímto slůvkem neodpovídá na anglické \"thank you\" -děkuji Vám"],
"Please sit down and join us":["prosím posaďte se a připojte se k nám"],
"Well done steak":["propečený biftek medium done"],
"What about ...":["a co ..."],
"What about me":["a co já?, nebo: a co pro mne?"],
"What about you?":["no a co Vy,"],
"What can I do for you":["co mohu pro Vás udělat, čím mohu sloužit"],
"What do I do with it":["What am I to do with it"],
"What do you do":["co děláte?"],
"What do you make of it?":["co z toho usuzujete?"],
"what is it":["co je to ( hovorově: Co je? Co máš nového?)"],
"What is the time?":["kolik je hodin?"],
"What of it":["no a co z toho"],
"What was on?":["co se dělo nebo co se hrálo?"],
"What was the matter":["co se stalo"],
"What was wrong with it?":["co s tím bylo?"],
"What will the people think about us":["co si o nás lidi pomyslí"],
"What will you have":["co si dáte? co račte poroučet? /také"],
"What's happened":["co se stalo"],
"What's his phone number":["jaké má telefonní číslo, jaké má číslo telefonu"],
"What's on your mind":["co máte na mysli"],
"What's that?":["co to?"],
"What's the big idea":["co je to za nápad"],
"What's up":["co je?"],
"What's use of":["jaký má smysl..."],
"Which is the way":["kudy se jde...?"],
"Who is starring?":["kdo hraje hlavní roli?"],
"Will that be of any help to you?":["pomůže Vám to?"],
"You are my only friend":["ty jsi mým jediným přítelem... /kyní/"],
"You are right":["máte pravdu As for the ..."],
"You are shadowed":["jste sledován, /stopován/"],
"You are telling me":["mně to budete povídat ..."],
"you are welcome":["jste vítán"],
"You bet":["/jedno z nejčastějších rčení/"],
"You don't have to be !":["nemusíte /být/"],
"You may leave now to carry on your duty":["můžete teď odejít, pokračovat ve službě"],
"You're kidding":["/slang/ Vy žertujete, děláte si legraci, srandu"],
"You're welcome":["jste vítán"],
"Your letter in hand":["obdrželi jsme Váš dopis"]
}